WITH
  expected_types AS (
    SELECT
      'INVOICENO' AS COLUMN_NAME,
      'VARCHAR' AS EXPECTED_DATA_TYPE
    UNION ALL
    SELECT
      'STOCKCODE',
      'INTEGER'
    UNION ALL
    SELECT
      'DESCRIPTION',
      'VARCHAR'
    UNION ALL
    SELECT
      'QUANTITY',
      'NUMBER'
    UNION ALL
    SELECT
      'INVOICEDATE',
      'TIMESTAMP_NTZ'
    UNION ALL
    SELECT
      'UNITPRICE',
      'NUMBER'
    UNION ALL
    SELECT
      'CUSTOMERID',
      'INTEGER'
    UNION ALL
    SELECT
      'COUNTRY',
      'VARCHAR'
  ),
  actual_types AS (
    SELECT
      COLUMN_NAME,
      DATA_TYPE AS ACTUAL_DATA_TYPE
    FROM
      INFORMATION_SCHEMA.COLUMNS
    WHERE
      TABLE_SCHEMA = 'RETAIL'
      AND TABLE_NAME = 'INVOICES_RAW_DATA'
  )
SELECT
  e.COLUMN_NAME,
  e.EXPECTED_DATA_TYPE,
  a.ACTUAL_DATA_TYPE,
  CASE
    WHEN a.ACTUAL_DATA_TYPE IS NULL THEN 'MISSING'
    WHEN e.EXPECTED_DATA_TYPE = a.ACTUAL_DATA_TYPE THEN  'VALIDATED'
    WHEN e.EXPECTED_DATA_TYPE != a.ACTUAL_DATA_TYPE THEN  'TYPE MISMATCH'
  END AS STATUS
FROM
  expected_types e
  LEFT JOIN actual_types a ON e.COLUMN_NAME = a.COLUMN_NAME
