are these fine to us :

  version: 2

  models:
    - name: dq_range_checks

      columns:

        - name: INVOICENO

        - name: STOCKCODE

        - name: QUANTITY

        - name: INVOICEDATE

        - name: UNITPRICE

        - name: CUSTOMERID

        - name: COUNTRY

    - name: dq_data_type_checks

      columns:
        - name: INVOICENO

        - name: STOCKCODE

        - name: QUANTITY

        - name: INVOICEDATE

        - name: UNITPRICE

        - name: CUSTOMERID

        - name: COUNTRY