version: 2

models:

  - name: dim_customer
    columns:
      - name: customer_key
        tests:
          - not_null
          - unique

      - name: customer_id

      - name: country


  - name: dim_product
    columns:
      - name: product_key
        tests:
          - not_null
          - unique

      - name: stock_code

      - name: description


  - name: dim_date
    columns:
      - name: date_key
        tests:
          - not_null
          - unique

      - name: invoice_date

      - name: i_year

      - name: i_month

      - name: i_day


  - name: fact_transaction
    columns:
      - name: transaction_key
        tests:
          - not_null
          - unique

      - name: customer_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_key

      - name: product_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_key

      - name: date_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key

      - name: invoice_id

      - name: is_cancelled

      - name: quantity

      - name: unit_price

      - name: total_cost