version: 2

models:

    - name: dim_customer

      columns:
        - name: customer_key

        - name: customer_id

        - name: country

    - name: dim_product

      columns:
        - name: product_key

        - name: stock_code

        - name: description

    - name: dim_date

      columns:
        - name: date_key

        - name: invoice_date

        - name: i_year

        - name: i_month

        - name: i_day