version: 2

models:

    - name: dim_customer

      columns:
        - name: customer_key

        - name: customer_id

        - name: country

    - name: dim_product

      columns:
        - name: product_key

        - name: stock_code

        - name: description